version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgresql_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - banking-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - banking-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak_container
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql_container:5432/keycloak_db
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
    ports:
      - "9098:8080"
    depends_on:
      - postgres
    networks:
      - banking-network
    volumes:
      - ./keycloak-realm-config.json:/opt/keycloak/data/import/realm-config.json
    command:
      - "start-dev"
      - "--import-realm"


  maildev:
    image: maildev/maildev
    container_name: maildev_container
    ports:
      - "1025:1025" # SMTP Port
      - "1080:1080" # Web UI Port
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge

volumes:
  postgres-data:
